package kstradeapija;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.ann.Virtual;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : linuxapi/CTP/kstradeapija.h:28</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("kstradeapija") 
public class CThostFtdcTraderSpi extends CPPObject {
	/**
	 * \u00b5\u00b1\u00bf\u00cd\u00bb\u00a7\u00b6\u00cb\u00d3\u00eb\u0153\u00bb\u00d2\u00d7\u00ba\u00f3\u00cc\u0161\u0153\u0161\u00c1\u00a2\u00c6\u00f0\u00cd\u0161\u00d0\u00c5\u00c1\u00ac\u0153\u00d3\u00ca\u00b1\u00a3\u0161\u00bb\u00b9\u00ce\u017d\u00b5\u00c7\u00c2\u0152\u00c7\u00b0\u00a3\u00a9\u00a3\u00ac\u017e\u00c3\u00b7\u0153\u00b7\u0161\u00b1\u00bb\u00b5\u00f7\u00d3\u00c3\u00a1\u00a3<br>
	 * Original signature : <code>void OnFrontConnected()</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:32</i>
	 */
	@Virtual(0) 
	native public void OnFrontConnected();
	/**
	 * 0x2004 \u00b7\u00fe\u00ce\u00f1\u00c6\u00f7\u00d6\u00f7\u00b6\u00af\u00b6\u00cf\u00bf\u00aa<br>
	 * Original signature : <code>void OnFrontDisconnected(int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:42</i>
	 */
	@Virtual(1) 
	native public void OnFrontDisconnected(int nReason);
	/**
	 * @param nTimeLapse \u0178\u00e0\u00c0\u00eb\u00c9\u00cf\u017d\u00ce\u0153\u00d3\u00ca\u00d5\u00b1\u0161\u00ce\u00c4\u00b5\u00c4\u00ca\u00b1\u0152\u00e4<br>
	 * Original signature : <code>void OnHeartBeatWarning(int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:46</i>
	 */
	@Virtual(2) 
	native public void OnHeartBeatWarning(int nTimeLapse);
	/**
	 * \u00bf\u00cd\u00bb\u00a7\u00b6\u00cb\u00c8\u00cf\u00d6\u20ac\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspAuthenticate(CThostFtdcRspAuthenticateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:49</i>
	 */
	@Virtual(3) 
	native public void OnRspAuthenticate(Pointer<CThostFtdcRspAuthenticateField > pRspAuthenticateField, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspAuthenticate(Pointer.getPeer(pRspAuthenticateField), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(3)
	//protected native void OnRspAuthenticate(@Ptr long pRspAuthenticateField, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00b5\u00c7\u00c2\u0152\u00c7\u00eb\u00c7\u00f3\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspUserLogin(CThostFtdcRspUserLoginField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:52</i>
	 */
	@Virtual(4) 
	native public void OnRspUserLogin(Pointer<CThostFtdcRspUserLoginField > pRspUserLogin, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspUserLogin(Pointer.getPeer(pRspUserLogin), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(4)
	//protected native void OnRspUserLogin(@Ptr long pRspUserLogin, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00b5\u00c7\u00b3\u00f6\u00c7\u00eb\u00c7\u00f3\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspUserLogout(CThostFtdcUserLogoutField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:55</i>
	 */
	@Virtual(5) 
	native public void OnRspUserLogout(Pointer<CThostFtdcUserLogoutField > pUserLogout, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspUserLogout(Pointer.getPeer(pUserLogout), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(5)
	//protected native void OnRspUserLogout(@Ptr long pUserLogout, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00d3\u00c3\u00bb\u00a7\u00bf\u00da\u00c1\u00ee\u017e\u00fc\u00d0\u00c2\u00c7\u00eb\u00c7\u00f3\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspUserPasswordUpdate(CThostFtdcUserPasswordUpdateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:58</i>
	 */
	@Virtual(6) 
	native public void OnRspUserPasswordUpdate(Pointer<CThostFtdcUserPasswordUpdateField > pUserPasswordUpdate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspUserPasswordUpdate(Pointer.getPeer(pUserPasswordUpdate), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(6)
	//protected native void OnRspUserPasswordUpdate(@Ptr long pUserPasswordUpdate, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00d7\u00ca\u0153\u00f0\u00d5\u00cb\u00bb\u00a7\u00bf\u00da\u00c1\u00ee\u017e\u00fc\u00d0\u00c2\u00c7\u00eb\u00c7\u00f3\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspTradingAccountPasswordUpdate(CThostFtdcTradingAccountPasswordUpdateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:61</i>
	 */
	@Virtual(7) 
	native public void OnRspTradingAccountPasswordUpdate(Pointer<CThostFtdcTradingAccountPasswordUpdateField > pTradingAccountPasswordUpdate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspTradingAccountPasswordUpdate(Pointer.getPeer(pTradingAccountPasswordUpdate), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(7)
	//protected native void OnRspTradingAccountPasswordUpdate(@Ptr long pTradingAccountPasswordUpdate, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00b1\u0161\u00b5\u00a5\u00c2\u0152\u00c8\u00eb\u00c7\u00eb\u00c7\u00f3\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspOrderInsert(CThostFtdcInputOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:64</i>
	 */
	@Virtual(8) 
	native public void OnRspOrderInsert(Pointer<CThostFtdcInputOrderField > pInputOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspOrderInsert(Pointer.getPeer(pInputOrder), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(8)
	//protected native void OnRspOrderInsert(@Ptr long pInputOrder, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00d4\u20ac\u00c2\u00f1\u00b5\u00a5\u00c2\u0152\u00c8\u00eb\u00c7\u00eb\u00c7\u00f3\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspParkedOrderInsert(CThostFtdcParkedOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:67</i>
	 */
	@Virtual(9) 
	native public void OnRspParkedOrderInsert(Pointer<CThostFtdcParkedOrderField > pParkedOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspParkedOrderInsert(Pointer.getPeer(pParkedOrder), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(9)
	//protected native void OnRspParkedOrderInsert(@Ptr long pParkedOrder, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00d4\u20ac\u00c2\u00f1\u00b3\u00b7\u00b5\u00a5\u00c2\u0152\u00c8\u00eb\u00c7\u00eb\u00c7\u00f3\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspParkedOrderAction(CThostFtdcParkedOrderActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:70</i>
	 */
	@Virtual(10) 
	native public void OnRspParkedOrderAction(Pointer<CThostFtdcParkedOrderActionField > pParkedOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspParkedOrderAction(Pointer.getPeer(pParkedOrderAction), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(10)
	//protected native void OnRspParkedOrderAction(@Ptr long pParkedOrderAction, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00b1\u0161\u00b5\u00a5\u00b2\u00d9\u00d7\u00f7\u00c7\u00eb\u00c7\u00f3\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspOrderAction(CThostFtdcInputOrderActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:73</i>
	 */
	@Virtual(11) 
	native public void OnRspOrderAction(Pointer<CThostFtdcInputOrderActionField > pInputOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspOrderAction(Pointer.getPeer(pInputOrderAction), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(11)
	//protected native void OnRspOrderAction(@Ptr long pInputOrderAction, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00b2\u00e9\u00d1\u00af\u00d7\u00ee\u017d\u00f3\u00b1\u0161\u00b5\u00a5\u00ca\u00fd\u00c1\u00bf\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQueryMaxOrderVolume(CThostFtdcQueryMaxOrderVolumeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:76</i>
	 */
	@Virtual(12) 
	native public void OnRspQueryMaxOrderVolume(Pointer<CThostFtdcQueryMaxOrderVolumeField > pQueryMaxOrderVolume, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQueryMaxOrderVolume(Pointer.getPeer(pQueryMaxOrderVolume), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(12)
	//protected native void OnRspQueryMaxOrderVolume(@Ptr long pQueryMaxOrderVolume, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00cd\u00b6\u00d7\u00ca\u00d5\u00df\u0153\u00e1\u00cb\u00e3\u0153\u00e1\u00b9\u00fb\u00c8\u00b7\u00c8\u00cf\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspSettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:79</i>
	 */
	@Virtual(13) 
	native public void OnRspSettlementInfoConfirm(Pointer<CThostFtdcSettlementInfoConfirmField > pSettlementInfoConfirm, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspSettlementInfoConfirm(Pointer.getPeer(pSettlementInfoConfirm), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(13)
	//protected native void OnRspSettlementInfoConfirm(@Ptr long pSettlementInfoConfirm, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c9\u0178\u00b3\u00fd\u00d4\u20ac\u00c2\u00f1\u00b5\u00a5\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspRemoveParkedOrder(CThostFtdcRemoveParkedOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:82</i>
	 */
	@Virtual(14) 
	native public void OnRspRemoveParkedOrder(Pointer<CThostFtdcRemoveParkedOrderField > pRemoveParkedOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspRemoveParkedOrder(Pointer.getPeer(pRemoveParkedOrder), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(14)
	//protected native void OnRspRemoveParkedOrder(@Ptr long pRemoveParkedOrder, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c9\u0178\u00b3\u00fd\u00d4\u20ac\u00c2\u00f1\u00b3\u00b7\u00b5\u00a5\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspRemoveParkedOrderAction(CThostFtdcRemoveParkedOrderActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:85</i>
	 */
	@Virtual(15) 
	native public void OnRspRemoveParkedOrderAction(Pointer<CThostFtdcRemoveParkedOrderActionField > pRemoveParkedOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspRemoveParkedOrderAction(Pointer.getPeer(pRemoveParkedOrderAction), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(15)
	//protected native void OnRspRemoveParkedOrderAction(@Ptr long pRemoveParkedOrderAction, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00b1\u0161\u00b5\u00a5\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryOrder(CThostFtdcOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:88</i>
	 */
	@Virtual(16) 
	native public void OnRspQryOrder(Pointer<CThostFtdcOrderField > pOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryOrder(Pointer.getPeer(pOrder), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(16)
	//protected native void OnRspQryOrder(@Ptr long pOrder, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00b3\u00c9\u0153\u00bb\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryTrade(CThostFtdcTradeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:91</i>
	 */
	@Virtual(17) 
	native public void OnRspQryTrade(Pointer<CThostFtdcTradeField > pTrade, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryTrade(Pointer.getPeer(pTrade), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(17)
	//protected native void OnRspQryTrade(@Ptr long pTrade, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00cd\u00b6\u00d7\u00ca\u00d5\u00df\u00b3\u00d6\u00b2\u00d6\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryInvestorPosition(CThostFtdcInvestorPositionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:94</i>
	 */
	@Virtual(18) 
	native public void OnRspQryInvestorPosition(Pointer<CThostFtdcInvestorPositionField > pInvestorPosition, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryInvestorPosition(Pointer.getPeer(pInvestorPosition), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(18)
	//protected native void OnRspQryInvestorPosition(@Ptr long pInvestorPosition, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d7\u00ca\u0153\u00f0\u00d5\u00cb\u00bb\u00a7\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryTradingAccount(CThostFtdcTradingAccountField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:97</i>
	 */
	@Virtual(19) 
	native public void OnRspQryTradingAccount(Pointer<CThostFtdcTradingAccountField > pTradingAccount, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryTradingAccount(Pointer.getPeer(pTradingAccount), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(19)
	//protected native void OnRspQryTradingAccount(@Ptr long pTradingAccount, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00cd\u00b6\u00d7\u00ca\u00d5\u00df\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryInvestor(CThostFtdcInvestorField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:100</i>
	 */
	@Virtual(20) 
	native public void OnRspQryInvestor(Pointer<CThostFtdcInvestorField > pInvestor, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryInvestor(Pointer.getPeer(pInvestor), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(20)
	//protected native void OnRspQryInvestor(@Ptr long pInvestor, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0153\u00bb\u00d2\u00d7\u00b1\u00e0\u00c2\u00eb\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryTradingCode(CThostFtdcTradingCodeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:103</i>
	 */
	@Virtual(21) 
	native public void OnRspQryTradingCode(Pointer<CThostFtdcTradingCodeField > pTradingCode, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryTradingCode(Pointer.getPeer(pTradingCode), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(21)
	//protected native void OnRspQryTradingCode(@Ptr long pTradingCode, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00ba\u00cf\u00d4\u0152\u00b1\u00a3\u00d6\u20ac\u0153\u00f0\u00c2\u00ca\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryInstrumentMarginRate(CThostFtdcInstrumentMarginRateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:106</i>
	 */
	@Virtual(22) 
	native public void OnRspQryInstrumentMarginRate(Pointer<CThostFtdcInstrumentMarginRateField > pInstrumentMarginRate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryInstrumentMarginRate(Pointer.getPeer(pInstrumentMarginRate), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(22)
	//protected native void OnRspQryInstrumentMarginRate(@Ptr long pInstrumentMarginRate, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00ba\u00cf\u00d4\u0152\u00ca\u00d6\u00d0\u00f8\u00b7\u00d1\u00c2\u00ca\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryInstrumentCommissionRate(CThostFtdcInstrumentCommissionRateField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:109</i>
	 */
	@Virtual(23) 
	native public void OnRspQryInstrumentCommissionRate(Pointer<CThostFtdcInstrumentCommissionRateField > pInstrumentCommissionRate, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryInstrumentCommissionRate(Pointer.getPeer(pInstrumentCommissionRate), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(23)
	//protected native void OnRspQryInstrumentCommissionRate(@Ptr long pInstrumentCommissionRate, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0153\u00bb\u00d2\u00d7\u00cb\u00f9\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryExchange(CThostFtdcExchangeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:112</i>
	 */
	@Virtual(24) 
	native public void OnRspQryExchange(Pointer<CThostFtdcExchangeField > pExchange, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryExchange(Pointer.getPeer(pExchange), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(24)
	//protected native void OnRspQryExchange(@Ptr long pExchange, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00ba\u00cf\u00d4\u0152\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryInstrument(CThostFtdcInstrumentField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:115</i>
	 */
	@Virtual(25) 
	native public void OnRspQryInstrument(Pointer<CThostFtdcInstrumentField > pInstrument, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryInstrument(Pointer.getPeer(pInstrument), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(25)
	//protected native void OnRspQryInstrument(@Ptr long pInstrument, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d0\u00d0\u00c7\u00e9\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryDepthMarketData(CThostFtdcDepthMarketDataField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:118</i>
	 */
	@Virtual(26) 
	native public void OnRspQryDepthMarketData(Pointer<CThostFtdcDepthMarketDataField > pDepthMarketData, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryDepthMarketData(Pointer.getPeer(pDepthMarketData), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(26)
	//protected native void OnRspQryDepthMarketData(@Ptr long pDepthMarketData, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00cd\u00b6\u00d7\u00ca\u00d5\u00df\u0153\u00e1\u00cb\u00e3\u0153\u00e1\u00b9\u00fb\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQrySettlementInfo(CThostFtdcSettlementInfoField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:121</i>
	 */
	@Virtual(27) 
	native public void OnRspQrySettlementInfo(Pointer<CThostFtdcSettlementInfoField > pSettlementInfo, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQrySettlementInfo(Pointer.getPeer(pSettlementInfo), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(27)
	//protected native void OnRspQrySettlementInfo(@Ptr long pSettlementInfo, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d7\u00aa\u00d5\u00ca\u00d2\u00f8\u00d0\u00d0\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryTransferBank(CThostFtdcTransferBankField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:124</i>
	 */
	@Virtual(28) 
	native public void OnRspQryTransferBank(Pointer<CThostFtdcTransferBankField > pTransferBank, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryTransferBank(Pointer.getPeer(pTransferBank), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(28)
	//protected native void OnRspQryTransferBank(@Ptr long pTransferBank, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00cd\u00b6\u00d7\u00ca\u00d5\u00df\u00b3\u00d6\u00b2\u00d6\u00c3\u00f7\u00cf\u017e\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryInvestorPositionDetail(CThostFtdcInvestorPositionDetailField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:127</i>
	 */
	@Virtual(29) 
	native public void OnRspQryInvestorPositionDetail(Pointer<CThostFtdcInvestorPositionDetailField > pInvestorPositionDetail, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryInvestorPositionDetail(Pointer.getPeer(pInvestorPositionDetail), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(29)
	//protected native void OnRspQryInvestorPositionDetail(@Ptr long pInvestorPositionDetail, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00bf\u00cd\u00bb\u00a7\u00cd\u0161\u00d6\u00aa\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryNotice(CThostFtdcNoticeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:130</i>
	 */
	@Virtual(30)
    native public void OnRspQryNotice(Pointer<CThostFtdcNoticeField > pNotice, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryNotice(Pointer.getPeer(pNotice), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(30)
	//protected native void OnRspQryNotice(@Ptr long pNotice, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0153\u00e1\u00cb\u00e3\u00d0\u00c5\u00cf\u00a2\u00c8\u00b7\u00c8\u00cf\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQrySettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:133</i>
	 */
	@Virtual(31)
    native public void OnRspQrySettlementInfoConfirm(Pointer<CThostFtdcSettlementInfoConfirmField > pSettlementInfoConfirm, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQrySettlementInfoConfirm(Pointer.getPeer(pSettlementInfoConfirm), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(31)
	//protected native void OnRspQrySettlementInfoConfirm(@Ptr long pSettlementInfoConfirm, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00cd\u00b6\u00d7\u00ca\u00d5\u00df\u00b3\u00d6\u00b2\u00d6\u00c3\u00f7\u00cf\u017e\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryInvestorPositionCombineDetail(CThostFtdcInvestorPositionCombineDetailField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:136</i>
	 */
	@Virtual(32)
    native public void OnRspQryInvestorPositionCombineDetail(Pointer<CThostFtdcInvestorPositionCombineDetailField > pInvestorPositionCombineDetail, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryInvestorPositionCombineDetail(Pointer.getPeer(pInvestorPositionCombineDetail), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(32)
	//protected native void OnRspQryInvestorPositionCombineDetail(@Ptr long pInvestorPositionCombineDetail, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00b2\u00e9\u00d1\u00af\u00b1\u00a3\u00d6\u20ac\u0153\u00f0\u0152\u00e0\u00b9\u00dc\u00cf\u00b5\u00cd\u00b3\u0178\u00ad\u0152\u00cd\u00b9\u00ab\u00cb\u0178\u00d7\u00ca\u0153\u00f0\u00d5\u00cb\u00bb\u00a7\u00c3\u00dc\u00d4\u00bf\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryCFMMCTradingAccountKey(CThostFtdcCFMMCTradingAccountKeyField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:139</i>
	 */
	@Virtual(33)
    native public void OnRspQryCFMMCTradingAccountKey(Pointer<CThostFtdcCFMMCTradingAccountKeyField > pCFMMCTradingAccountKey, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryCFMMCTradingAccountKey(Pointer.getPeer(pCFMMCTradingAccountKey), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(33)
	//protected native void OnRspQryCFMMCTradingAccountKey(@Ptr long pCFMMCTradingAccountKey, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00b2\u00d6\u00b5\u00a5\u00d5\u00db\u00b5\u00d6\u00d0\u00c5\u00cf\u00a2\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryEWarrantOffset(CThostFtdcEWarrantOffsetField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:142</i>
	 */
	@Virtual(34)
    native public void OnRspQryEWarrantOffset(Pointer<CThostFtdcEWarrantOffsetField > pEWarrantOffset, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryEWarrantOffset(Pointer.getPeer(pEWarrantOffset), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(34)
	//protected native void OnRspQryEWarrantOffset(@Ptr long pEWarrantOffset, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d7\u00aa\u00d5\u00ca\u00c1\u00f7\u00cb\u00ae\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryTransferSerial(CThostFtdcTransferSerialField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:145</i>
	 */
	@Virtual(35)
    native public void OnRspQryTransferSerial(Pointer<CThostFtdcTransferSerialField > pTransferSerial, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryTransferSerial(Pointer.getPeer(pTransferSerial), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(35)
	//protected native void OnRspQryTransferSerial(@Ptr long pTransferSerial, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d2\u00f8\u00c6\u00da\u00c7\u00a9\u00d4\u0152\u00b9\u00d8\u00cf\u00b5\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryAccountregister(CThostFtdcAccountregisterField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:148</i>
	 */
	@Virtual(36)
    native public void OnRspQryAccountregister(Pointer<CThostFtdcAccountregisterField > pAccountregister, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryAccountregister(Pointer.getPeer(pAccountregister), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(36)
	//protected native void OnRspQryAccountregister(@Ptr long pAccountregister, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u017d\u00ed\u00ce\u00f3\u00d3\u0160\u017d\u00f0<br>
	 * Original signature : <code>void OnRspError(CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:151</i>
	 */
	@Virtual(37)
    native public void OnRspError(Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspError(Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(37)
	//protected native void OnRspError(@Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00b1\u0161\u00b5\u00a5\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnOrder(CThostFtdcOrderField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:154</i>
	 */
	@Virtual(38)
    native public void OnRtnOrder(Pointer<CThostFtdcOrderField > pOrder) ; // {
	//	OnRtnOrder(Pointer.getPeer(pOrder));
	//}
	//@Virtual(38)
	//protected native void OnRtnOrder(@Ptr long pOrder);
	/**
	 * \u00b3\u00c9\u0153\u00bb\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnTrade(CThostFtdcTradeField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:157</i>
	 */
	@Virtual(39)
    native public void OnRtnTrade(Pointer<CThostFtdcTradeField > pTrade) ; // {
	//	OnRtnTrade(Pointer.getPeer(pTrade));
	//}
	//@Virtual(39)
	//protected native void OnRtnTrade(@Ptr long pTrade);
	/**
	 * \u00b1\u0161\u00b5\u00a5\u00c2\u0152\u00c8\u00eb\u017d\u00ed\u00ce\u00f3\u00bb\u00d8\u00b1\u0161<br>
	 * Original signature : <code>void OnErrRtnOrderInsert(CThostFtdcInputOrderField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:160</i>
	 */
	@Virtual(40)
    native public void OnErrRtnOrderInsert(Pointer<CThostFtdcInputOrderField > pInputOrder, Pointer<CThostFtdcRspInfoField > pRspInfo) ; // {
	//	OnErrRtnOrderInsert(Pointer.getPeer(pInputOrder), Pointer.getPeer(pRspInfo));
	//}
	//@Virtual(40)
	//protected native void OnErrRtnOrderInsert(@Ptr long pInputOrder, @Ptr long pRspInfo);
	/**
	 * \u00b1\u0161\u00b5\u00a5\u00b2\u00d9\u00d7\u00f7\u017d\u00ed\u00ce\u00f3\u00bb\u00d8\u00b1\u0161<br>
	 * Original signature : <code>void OnErrRtnOrderAction(CThostFtdcOrderActionField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:163</i>
	 */
	@Virtual(41)
    native public void OnErrRtnOrderAction(Pointer<CThostFtdcOrderActionField > pOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo) ; // {
	//	OnErrRtnOrderAction(Pointer.getPeer(pOrderAction), Pointer.getPeer(pRspInfo));
	//}
	//@Virtual(41)
	//protected native void OnErrRtnOrderAction(@Ptr long pOrderAction, @Ptr long pRspInfo);
	/**
	 * \u00ba\u00cf\u00d4\u0152\u0153\u00bb\u00d2\u00d7\u00d7\u017d\u00cc\u00ac\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnInstrumentStatus(CThostFtdcInstrumentStatusField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:166</i>
	 */
	@Virtual(42)
    native public void OnRtnInstrumentStatus(Pointer<CThostFtdcInstrumentStatusField > pInstrumentStatus) ; // {
	//	OnRtnInstrumentStatus(Pointer.getPeer(pInstrumentStatus));
	//}
	//@Virtual(42)
	//protected native void OnRtnInstrumentStatus(@Ptr long pInstrumentStatus);
	/**
	 * \u0153\u00bb\u00d2\u00d7\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnTradingNotice(CThostFtdcTradingNoticeInfoField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:169</i>
	 */
	@Virtual(43)
    native public void OnRtnTradingNotice(Pointer<CThostFtdcTradingNoticeInfoField > pTradingNoticeInfo) ; // {
	//	OnRtnTradingNotice(Pointer.getPeer(pTradingNoticeInfo));
	//}
	//@Virtual(43)
	//protected native void OnRtnTradingNotice(@Ptr long pTradingNoticeInfo);
	/**
	 * \u00cc\u00e1\u00ca\u0178\u00cc\u00f5\u0152\u00fe\u00b5\u00a5\u00d0\u00a3\u00d1\u00e9\u017d\u00ed\u00ce\u00f3<br>
	 * Original signature : <code>void OnRtnErrorConditionalOrder(CThostFtdcErrorConditionalOrderField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:172</i>
	 */
	@Virtual(44)
    native public void OnRtnErrorConditionalOrder(Pointer<CThostFtdcErrorConditionalOrderField > pErrorConditionalOrder) ; // {
	//	OnRtnErrorConditionalOrder(Pointer.getPeer(pErrorConditionalOrder));
	//}
	//@Virtual(44)
	//protected native void OnRtnErrorConditionalOrder(@Ptr long pErrorConditionalOrder);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00c7\u00a9\u00d4\u0152\u00d2\u00f8\u00d0\u00d0\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryContractBank(CThostFtdcContractBankField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:175</i>
	 */
	@Virtual(45)
    native public void OnRspQryContractBank(Pointer<CThostFtdcContractBankField > pContractBank, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryContractBank(Pointer.getPeer(pContractBank), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(45)
	//protected native void OnRspQryContractBank(@Ptr long pContractBank, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d4\u20ac\u00c2\u00f1\u00b5\u00a5\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryParkedOrder(CThostFtdcParkedOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:178</i>
	 */
	@Virtual(46)
    native public void OnRspQryParkedOrder(Pointer<CThostFtdcParkedOrderField > pParkedOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryParkedOrder(Pointer.getPeer(pParkedOrder), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(46)
	//protected native void OnRspQryParkedOrder(@Ptr long pParkedOrder, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d4\u20ac\u00c2\u00f1\u00b3\u00b7\u00b5\u00a5\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryParkedOrderAction(CThostFtdcParkedOrderActionField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:181</i>
	 */
	@Virtual(47)
    native public void OnRspQryParkedOrderAction(Pointer<CThostFtdcParkedOrderActionField > pParkedOrderAction, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryParkedOrderAction(Pointer.getPeer(pParkedOrderAction), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(47)
	//protected native void OnRspQryParkedOrderAction(@Ptr long pParkedOrderAction, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0153\u00bb\u00d2\u00d7\u00cd\u0161\u00d6\u00aa\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryTradingNotice(CThostFtdcTradingNoticeField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:184</i>
	 */
	@Virtual(48)
    native public void OnRspQryTradingNotice(Pointer<CThostFtdcTradingNoticeField > pTradingNotice, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryTradingNotice(Pointer.getPeer(pTradingNotice), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(48)
	//protected native void OnRspQryTradingNotice(@Ptr long pTradingNotice, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0178\u00ad\u0152\u00cd\u00b9\u00ab\u00cb\u0178\u0153\u00bb\u00d2\u00d7\u00b2\u00ce\u00ca\u00fd\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryBrokerTradingParams(CThostFtdcBrokerTradingParamsField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:187</i>
	 */
	@Virtual(49)
    native public void OnRspQryBrokerTradingParams(Pointer<CThostFtdcBrokerTradingParamsField > pBrokerTradingParams, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryBrokerTradingParams(Pointer.getPeer(pBrokerTradingParams), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(49)
	//protected native void OnRspQryBrokerTradingParams(@Ptr long pBrokerTradingParams, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0178\u00ad\u0152\u00cd\u00b9\u00ab\u00cb\u0178\u0153\u00bb\u00d2\u00d7\u00cb\u00e3\u00b7\u0161\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspQryBrokerTradingAlgos(CThostFtdcBrokerTradingAlgosField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:190</i>
	 */
	@Virtual(50)
    native public void OnRspQryBrokerTradingAlgos(Pointer<CThostFtdcBrokerTradingAlgosField > pBrokerTradingAlgos, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryBrokerTradingAlgos(Pointer.getPeer(pBrokerTradingAlgos), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(50)
	//protected native void OnRspQryBrokerTradingAlgos(@Ptr long pBrokerTradingAlgos, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00d2\u00f8\u00d0\u00d0\u00b7\u00a2\u00c6\u00f0\u00d2\u00f8\u00d0\u00d0\u00d7\u00ca\u0153\u00f0\u00d7\u00aa\u00c6\u00da\u00bb\u00f5\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnFromBankToFutureByBank(CThostFtdcRspTransferField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:193</i>
	 */
	@Virtual(51) 
	native public void OnRtnFromBankToFutureByBank(Pointer<CThostFtdcRspTransferField > pRspTransfer) ; // {
	//	OnRtnFromBankToFutureByBank(Pointer.getPeer(pRspTransfer));
	//}
	//@Virtual(51)
	//protected native void OnRtnFromBankToFutureByBank(@Ptr long pRspTransfer);
	/**
	 * \u00d2\u00f8\u00d0\u00d0\u00b7\u00a2\u00c6\u00f0\u00c6\u00da\u00bb\u00f5\u00d7\u00ca\u0153\u00f0\u00d7\u00aa\u00d2\u00f8\u00d0\u00d0\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnFromFutureToBankByBank(CThostFtdcRspTransferField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:196</i>
	 */
	@Virtual(52)
    native public void OnRtnFromFutureToBankByBank(Pointer<CThostFtdcRspTransferField > pRspTransfer) ; // {
	//	OnRtnFromFutureToBankByBank(Pointer.getPeer(pRspTransfer));
	//}
	//@Virtual(52)
	//protected native void OnRtnFromFutureToBankByBank(@Ptr long pRspTransfer);
	/**
	 * \u00d2\u00f8\u00d0\u00d0\u00b7\u00a2\u00c6\u00f0\u00b3\u00e5\u00d5\u00fd\u00d2\u00f8\u00d0\u00d0\u00d7\u00aa\u00c6\u00da\u00bb\u00f5\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnRepealFromBankToFutureByBank(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:199</i>
	 */
	@Virtual(53) 
	native public void OnRtnRepealFromBankToFutureByBank(Pointer<CThostFtdcRspRepealField > pRspRepeal) ; // {
	//	OnRtnRepealFromBankToFutureByBank(Pointer.getPeer(pRspRepeal));
	//}
	//@Virtual(53)
	//protected native void OnRtnRepealFromBankToFutureByBank(@Ptr long pRspRepeal);
	/**
	 * \u00d2\u00f8\u00d0\u00d0\u00b7\u00a2\u00c6\u00f0\u00b3\u00e5\u00d5\u00fd\u00c6\u00da\u00bb\u00f5\u00d7\u00aa\u00d2\u00f8\u00d0\u00d0\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnRepealFromFutureToBankByBank(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:202</i>
	 */
	@Virtual(54) 
	native public void OnRtnRepealFromFutureToBankByBank(Pointer<CThostFtdcRspRepealField > pRspRepeal) ; // {
	//	OnRtnRepealFromFutureToBankByBank(Pointer.getPeer(pRspRepeal));
	//}
	//@Virtual(54)
	//protected native void OnRtnRepealFromFutureToBankByBank(@Ptr long pRspRepeal);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00d2\u00f8\u00d0\u00d0\u00d7\u00ca\u0153\u00f0\u00d7\u00aa\u00c6\u00da\u00bb\u00f5\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnFromBankToFutureByFuture(CThostFtdcRspTransferField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:205</i>
	 */
	@Virtual(55)
    native public void OnRtnFromBankToFutureByFuture(Pointer<CThostFtdcRspTransferField > pRspTransfer) ; // {
	//	OnRtnFromBankToFutureByFuture(Pointer.getPeer(pRspTransfer));
	//}
	//@Virtual(55)
	//protected native void OnRtnFromBankToFutureByFuture(@Ptr long pRspTransfer);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00c6\u00da\u00bb\u00f5\u00d7\u00ca\u0153\u00f0\u00d7\u00aa\u00d2\u00f8\u00d0\u00d0\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnFromFutureToBankByFuture(CThostFtdcRspTransferField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:208</i>
	 */
	@Virtual(56)
    native public void OnRtnFromFutureToBankByFuture(Pointer<CThostFtdcRspTransferField > pRspTransfer) ; // {
	//	OnRtnFromFutureToBankByFuture(Pointer.getPeer(pRspTransfer));
	//}
	//@Virtual(56)
	//protected native void OnRtnFromFutureToBankByFuture(@Ptr long pRspTransfer);
	/**
	 * \u00cf\u00b5\u00cd\u00b3\u00d4\u00cb\u00d0\u00d0\u00ca\u00b1\u00c6\u00da\u00bb\u00f5\u00b6\u00cb\u00ca\u00d6\u00b9\u20ac\u00b7\u00a2\u00c6\u00f0\u00b3\u00e5\u00d5\u00fd\u00d2\u00f8\u00d0\u00d0\u00d7\u00aa\u00c6\u00da\u00bb\u00f5\u00c7\u00eb\u00c7\u00f3\u00a3\u00ac\u00d2\u00f8\u00d0\u00d0\u017d\u0160\u00c0\u00ed\u00cd\u00ea\u00b1\u00cf\u00ba\u00f3\u00b1\u0161\u00c5\u00cc\u00b7\u00a2\u00bb\u00d8\u00b5\u00c4\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnRepealFromBankToFutureByFutureManual(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:211</i>
	 */
	@Virtual(57)
    native public void OnRtnRepealFromBankToFutureByFutureManual(Pointer<CThostFtdcRspRepealField > pRspRepeal) ; // {
	//	OnRtnRepealFromBankToFutureByFutureManual(Pointer.getPeer(pRspRepeal));
	//}
	//@Virtual(57)
	//protected native void OnRtnRepealFromBankToFutureByFutureManual(@Ptr long pRspRepeal);
	/**
	 * \u00cf\u00b5\u00cd\u00b3\u00d4\u00cb\u00d0\u00d0\u00ca\u00b1\u00c6\u00da\u00bb\u00f5\u00b6\u00cb\u00ca\u00d6\u00b9\u20ac\u00b7\u00a2\u00c6\u00f0\u00b3\u00e5\u00d5\u00fd\u00c6\u00da\u00bb\u00f5\u00d7\u00aa\u00d2\u00f8\u00d0\u00d0\u00c7\u00eb\u00c7\u00f3\u00a3\u00ac\u00d2\u00f8\u00d0\u00d0\u017d\u0160\u00c0\u00ed\u00cd\u00ea\u00b1\u00cf\u00ba\u00f3\u00b1\u0161\u00c5\u00cc\u00b7\u00a2\u00bb\u00d8\u00b5\u00c4\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnRepealFromFutureToBankByFutureManual(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:214</i>
	 */
	@Virtual(58)
    native public void OnRtnRepealFromFutureToBankByFutureManual(Pointer<CThostFtdcRspRepealField > pRspRepeal) ; // {
	//	OnRtnRepealFromFutureToBankByFutureManual(Pointer.getPeer(pRspRepeal));
	//}
	//@Virtual(58)
	//protected native void OnRtnRepealFromFutureToBankByFutureManual(@Ptr long pRspRepeal);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00b2\u00e9\u00d1\u00af\u00d2\u00f8\u00d0\u00d0\u00d3\u00e0\u00b6\u00ee\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnQueryBankBalanceByFuture(CThostFtdcNotifyQueryAccountField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:217</i>
	 */
	@Virtual(59)
    native public void OnRtnQueryBankBalanceByFuture(Pointer<CThostFtdcNotifyQueryAccountField > pNotifyQueryAccount) ; // {
	//	OnRtnQueryBankBalanceByFuture(Pointer.getPeer(pNotifyQueryAccount));
	//}
	//@Virtual(59)
	//protected native void OnRtnQueryBankBalanceByFuture(@Ptr long pNotifyQueryAccount);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00d2\u00f8\u00d0\u00d0\u00d7\u00ca\u0153\u00f0\u00d7\u00aa\u00c6\u00da\u00bb\u00f5\u017d\u00ed\u00ce\u00f3\u00bb\u00d8\u00b1\u0161<br>
	 * Original signature : <code>void OnErrRtnBankToFutureByFuture(CThostFtdcReqTransferField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:220</i>
	 */
	@Virtual(60)
    native public void OnErrRtnBankToFutureByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, Pointer<CThostFtdcRspInfoField > pRspInfo) ; // {
	//	OnErrRtnBankToFutureByFuture(Pointer.getPeer(pReqTransfer), Pointer.getPeer(pRspInfo));
	//}
	//@Virtual(60)
	//protected native void OnErrRtnBankToFutureByFuture(@Ptr long pReqTransfer, @Ptr long pRspInfo);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00c6\u00da\u00bb\u00f5\u00d7\u00ca\u0153\u00f0\u00d7\u00aa\u00d2\u00f8\u00d0\u00d0\u017d\u00ed\u00ce\u00f3\u00bb\u00d8\u00b1\u0161<br>
	 * Original signature : <code>void OnErrRtnFutureToBankByFuture(CThostFtdcReqTransferField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:223</i>
	 */
	@Virtual(61)
    native public void OnErrRtnFutureToBankByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, Pointer<CThostFtdcRspInfoField > pRspInfo) ; // {
	//	OnErrRtnFutureToBankByFuture(Pointer.getPeer(pReqTransfer), Pointer.getPeer(pRspInfo));
	//}
	//@Virtual(61)
	//protected native void OnErrRtnFutureToBankByFuture(@Ptr long pReqTransfer, @Ptr long pRspInfo);
	/**
	 * \u00cf\u00b5\u00cd\u00b3\u00d4\u00cb\u00d0\u00d0\u00ca\u00b1\u00c6\u00da\u00bb\u00f5\u00b6\u00cb\u00ca\u00d6\u00b9\u20ac\u00b7\u00a2\u00c6\u00f0\u00b3\u00e5\u00d5\u00fd\u00d2\u00f8\u00d0\u00d0\u00d7\u00aa\u00c6\u00da\u00bb\u00f5\u017d\u00ed\u00ce\u00f3\u00bb\u00d8\u00b1\u0161<br>
	 * Original signature : <code>void OnErrRtnRepealBankToFutureByFutureManual(CThostFtdcReqRepealField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:226</i>
	 */
	@Virtual(62)
    native public void OnErrRtnRepealBankToFutureByFutureManual(Pointer<CThostFtdcReqRepealField > pReqRepeal, Pointer<CThostFtdcRspInfoField > pRspInfo) ; // {
	//	OnErrRtnRepealBankToFutureByFutureManual(Pointer.getPeer(pReqRepeal), Pointer.getPeer(pRspInfo));
	//}
	//@Virtual(62)
	//protected native void OnErrRtnRepealBankToFutureByFutureManual(@Ptr long pReqRepeal, @Ptr long pRspInfo);
	/**
	 * \u00cf\u00b5\u00cd\u00b3\u00d4\u00cb\u00d0\u00d0\u00ca\u00b1\u00c6\u00da\u00bb\u00f5\u00b6\u00cb\u00ca\u00d6\u00b9\u20ac\u00b7\u00a2\u00c6\u00f0\u00b3\u00e5\u00d5\u00fd\u00c6\u00da\u00bb\u00f5\u00d7\u00aa\u00d2\u00f8\u00d0\u00d0\u017d\u00ed\u00ce\u00f3\u00bb\u00d8\u00b1\u0161<br>
	 * Original signature : <code>void OnErrRtnRepealFutureToBankByFutureManual(CThostFtdcReqRepealField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:229</i>
	 */
	@Virtual(63)
    native public void OnErrRtnRepealFutureToBankByFutureManual(Pointer<CThostFtdcReqRepealField > pReqRepeal, Pointer<CThostFtdcRspInfoField > pRspInfo) ; // {
	//	OnErrRtnRepealFutureToBankByFutureManual(Pointer.getPeer(pReqRepeal), Pointer.getPeer(pRspInfo));
	//}
	//@Virtual(63)
	//protected native void OnErrRtnRepealFutureToBankByFutureManual(@Ptr long pReqRepeal, @Ptr long pRspInfo);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00b2\u00e9\u00d1\u00af\u00d2\u00f8\u00d0\u00d0\u00d3\u00e0\u00b6\u00ee\u017d\u00ed\u00ce\u00f3\u00bb\u00d8\u00b1\u0161<br>
	 * Original signature : <code>void OnErrRtnQueryBankBalanceByFuture(CThostFtdcReqQueryAccountField*, CThostFtdcRspInfoField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:232</i>
	 */
	@Virtual(64)
    native public void OnErrRtnQueryBankBalanceByFuture(Pointer<CThostFtdcReqQueryAccountField > pReqQueryAccount, Pointer<CThostFtdcRspInfoField > pRspInfo) ; // {
	//	OnErrRtnQueryBankBalanceByFuture(Pointer.getPeer(pReqQueryAccount), Pointer.getPeer(pRspInfo));
	//}
	//@Virtual(64)
	//protected native void OnErrRtnQueryBankBalanceByFuture(@Ptr long pReqQueryAccount, @Ptr long pRspInfo);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00b3\u00e5\u00d5\u00fd\u00d2\u00f8\u00d0\u00d0\u00d7\u00aa\u00c6\u00da\u00bb\u00f5\u00c7\u00eb\u00c7\u00f3\u00a3\u00ac\u00d2\u00f8\u00d0\u00d0\u017d\u0160\u00c0\u00ed\u00cd\u00ea\u00b1\u00cf\u00ba\u00f3\u00b1\u0161\u00c5\u00cc\u00b7\u00a2\u00bb\u00d8\u00b5\u00c4\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnRepealFromBankToFutureByFuture(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:235</i>
	 */
	@Virtual(65)
    native public void OnRtnRepealFromBankToFutureByFuture(Pointer<CThostFtdcRspRepealField > pRspRepeal) ; // {
	//	OnRtnRepealFromBankToFutureByFuture(Pointer.getPeer(pRspRepeal));
	//}
	//@Virtual(65)
	//protected native void OnRtnRepealFromBankToFutureByFuture(@Ptr long pRspRepeal);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00b3\u00e5\u00d5\u00fd\u00c6\u00da\u00bb\u00f5\u00d7\u00aa\u00d2\u00f8\u00d0\u00d0\u00c7\u00eb\u00c7\u00f3\u00a3\u00ac\u00d2\u00f8\u00d0\u00d0\u017d\u0160\u00c0\u00ed\u00cd\u00ea\u00b1\u00cf\u00ba\u00f3\u00b1\u0161\u00c5\u00cc\u00b7\u00a2\u00bb\u00d8\u00b5\u00c4\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnRepealFromFutureToBankByFuture(CThostFtdcRspRepealField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:238</i>
	 */
	@Virtual(66)
    native public void OnRtnRepealFromFutureToBankByFuture(Pointer<CThostFtdcRspRepealField > pRspRepeal) ; // {
	//	OnRtnRepealFromFutureToBankByFuture(Pointer.getPeer(pRspRepeal));
	//}
	//@Virtual(66)
	//protected native void OnRtnRepealFromFutureToBankByFuture(@Ptr long pRspRepeal);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00d2\u00f8\u00d0\u00d0\u00d7\u00ca\u0153\u00f0\u00d7\u00aa\u00c6\u00da\u00bb\u00f5\u00d3\u0160\u017d\u00f0<br>
	 * Original signature : <code>void OnRspFromBankToFutureByFuture(CThostFtdcReqTransferField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:241</i>
	 */
	@Virtual(67)
    native public void OnRspFromBankToFutureByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspFromBankToFutureByFuture(Pointer.getPeer(pReqTransfer), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(67)
	//protected native void OnRspFromBankToFutureByFuture(@Ptr long pReqTransfer, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00c6\u00da\u00bb\u00f5\u00d7\u00ca\u0153\u00f0\u00d7\u00aa\u00d2\u00f8\u00d0\u00d0\u00d3\u0160\u017d\u00f0<br>
	 * Original signature : <code>void OnRspFromFutureToBankByFuture(CThostFtdcReqTransferField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:244</i>
	 */
	@Virtual(68)
    native public void OnRspFromFutureToBankByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspFromFutureToBankByFuture(Pointer.getPeer(pReqTransfer), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(68)
	//protected native void OnRspFromFutureToBankByFuture(@Ptr long pReqTransfer, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00b2\u00e9\u00d1\u00af\u00d2\u00f8\u00d0\u00d0\u00d3\u00e0\u00b6\u00ee\u00d3\u0160\u017d\u00f0<br>
	 * Original signature : <code>void OnRspQueryBankAccountMoneyByFuture(CThostFtdcReqQueryAccountField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:247</i>
	 */
	@Virtual(69)
    native public void OnRspQueryBankAccountMoneyByFuture(Pointer<CThostFtdcReqQueryAccountField > pReqQueryAccount, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQueryBankAccountMoneyByFuture(Pointer.getPeer(pReqQueryAccount), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(69)
	//protected native void OnRspQueryBankAccountMoneyByFuture(@Ptr long pReqQueryAccount, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00d2\u00f8\u00d0\u00d0\u00b7\u00a2\u00c6\u00f0\u00d2\u00f8\u00c6\u00da\u00bf\u00aa\u00bb\u00a7\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnOpenAccountByBank(CThostFtdcOpenAccountField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:250</i>
	 */
	@Virtual(70)
    native public void OnRtnOpenAccountByBank(Pointer<CThostFtdcOpenAccountField > pOpenAccount) ; // {
	//	OnRtnOpenAccountByBank(Pointer.getPeer(pOpenAccount));
	//}
	//@Virtual(70)
	//protected native void OnRtnOpenAccountByBank(@Ptr long pOpenAccount);
	/**
	 * \u00d2\u00f8\u00d0\u00d0\u00b7\u00a2\u00c6\u00f0\u00d2\u00f8\u00c6\u00da\u00cf\u00fa\u00bb\u00a7\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnCancelAccountByBank(CThostFtdcCancelAccountField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:253</i>
	 */
	@Virtual(71)
    native public void OnRtnCancelAccountByBank(Pointer<CThostFtdcCancelAccountField > pCancelAccount) ; // {
	//	OnRtnCancelAccountByBank(Pointer.getPeer(pCancelAccount));
	//}
	//@Virtual(71)
	//protected native void OnRtnCancelAccountByBank(@Ptr long pCancelAccount);
	/**
	 * \u00d2\u00f8\u00d0\u00d0\u00b7\u00a2\u00c6\u00f0\u00b1\u00e4\u017e\u00fc\u00d2\u00f8\u00d0\u00d0\u00d5\u00cb\u00ba\u00c5\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>void OnRtnChangeAccountByBank(CThostFtdcChangeAccountField*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:256</i>
	 */
	@Virtual(72)
    native public void OnRtnChangeAccountByBank(Pointer<CThostFtdcChangeAccountField > pChangeAccount) ; // {
	//	OnRtnChangeAccountByBank(Pointer.getPeer(pChangeAccount));
	//}
	//@Virtual(72)
	//protected native void OnRtnChangeAccountByBank(@Ptr long pChangeAccount);
	/**
	 * \u00b2\u00e9\u00d1\u00af\u00bf\u00aa\u00c5\u00cc\u00c7\u00b0\u00b5\u00c4\u00b3\u00d6\u00b2\u00d6\u00c3\u00f7\u00cf\u017e\u00d3\u0160\u017d\u00f0(20110808)<br>
	 * Original signature : <code>void OnRspQryInvestorOpenPosition(CThostFtdcInvestorPositionDetailField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:259</i>
	 */
	@Virtual(73)
    native public void OnRspQryInvestorOpenPosition(Pointer<CThostFtdcInvestorPositionDetailField > pInvestorPositionDetail, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryInvestorOpenPosition(Pointer.getPeer(pInvestorPositionDetail), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(73)
	//protected native void OnRspQryInvestorOpenPosition(@Ptr long pInvestorPositionDetail, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00b2\u00e9\u00d1\u00af\u00bf\u00aa\u00c5\u00cc\u00c7\u00b0\u00b5\u00c4\u00d7\u00e9\u00ba\u00cf\u00b3\u00d6\u00b2\u00d6\u00c3\u00f7\u00cf\u017e\u00d3\u0160\u017d\u00f0(20110808)<br>
	 * Original signature : <code>void OnRspQryInvestorOpenCombinePosition(CThostFtdcInvestorPositionCombineDetailField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:262</i>
	 */
	@Virtual(74)
    native public void OnRspQryInvestorOpenCombinePosition(Pointer<CThostFtdcInvestorPositionCombineDetailField > pInvestorPositionCombineDetail, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspQryInvestorOpenCombinePosition(Pointer.getPeer(pInvestorPositionCombineDetail), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(74)
	//protected native void OnRspQryInvestorOpenCombinePosition(@Ptr long pInvestorPositionCombineDetail, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	/**
	 * \u00c5\u00fa\u00c1\u00bf\u00b1\u0161\u00b5\u00a5\u00b3\u00b7\u00b3\u00fd\u00c7\u00eb\u00c7\u00f3\u00cf\u00ec\u00d3\u0160<br>
	 * Original signature : <code>void OnRspBulkCancelOrder(CThostFtdcBulkCancelOrderField*, CThostFtdcRspInfoField*, int, bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:265</i>
	 */
	@Virtual(75)
    native public void OnRspBulkCancelOrder(Pointer<CThostFtdcBulkCancelOrderField > pBulkCancelOrder, Pointer<CThostFtdcRspInfoField > pRspInfo, int nRequestID, boolean bIsLast) ; // {
	//	OnRspBulkCancelOrder(Pointer.getPeer(pBulkCancelOrder), Pointer.getPeer(pRspInfo), nRequestID, bIsLast);
	//}
	//@Virtual(75)
	//protected native void OnRspBulkCancelOrder(@Ptr long pBulkCancelOrder, @Ptr long pRspInfo, int nRequestID, boolean bIsLast);
	public CThostFtdcTraderSpi() {
		super();
	}
	public CThostFtdcTraderSpi(Pointer pointer) {
		super(pointer);
	}
}
