package kstradeapija;
import kstradeapija.KstradeapijaLibrary.THOST_TE_RESUME_TYPE;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Ptr;
import org.bridj.ann.Virtual;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : linuxapi/CTP/kstradeapija.h:269</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("kstradeapija") 
public class CThostFtdcTraderApi extends CPPObject {
	/**
	 * modify for udp marketdata<br>
	 * Original signature : <code>CThostFtdcTraderApi* CreateFtdcTraderApi(const char*, const bool)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:276</i>
	 */
	native public static Pointer<CThostFtdcTraderApi > CreateFtdcTraderApi(Pointer<Byte > pszFlowPath, boolean bIsUsingUdp) ; // {
	//	return Pointer.pointerToAddress(CreateFtdcTraderApi(Pointer.getPeer(pszFlowPath), bIsUsingUdp), CThostFtdcTraderApi.class);
	//}
	//@Ptr
	//protected native static long CreateFtdcTraderApi(@Ptr long pszFlowPath, boolean bIsUsingUdp);
	/**
	 * @remark \u00b2\u00bb\u00d4\u00d9\u00ca\u00b9\u00d3\u00c3\u00b1\u0178\u0153\u00d3\u00bf\u00da\u00b6\u00d4\u00cf\u00f3\u00ca\u00b1,\u00b5\u00f7\u00d3\u00c3\u017e\u00c3\u00ba\u00af\u00ca\u00fd\u00c9\u0178\u00b3\u00fd\u0153\u00d3\u00bf\u00da\u00b6\u00d4\u00cf\u00f3<br>
	 * Original signature : <code>void Release()</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:280</i>
	 */
	@Virtual(0) 
	native public void Release();
	/**
	 * @remark \u00b3\u00f5\u00ca\u0152\u00bb\u00af\u00d4\u00cb\u00d0\u00d0\u00bb\u00b7\u0178\u00b3,\u00d6\u00bb\u00d3\u00d0\u00b5\u00f7\u00d3\u00c3\u00ba\u00f3,\u0153\u00d3\u00bf\u00da\u00b2\u00c5\u00bf\u00aa\u00ca\u0152\u00b9\u20ac\u00d7\u00f7<br>
	 * Original signature : <code>void Init()</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:284</i>
	 */
	@Virtual(1) 
	native public void Init();
	/**
	 * @return \u00cf\u00df\u00b3\u00cc\u00cd\u00cb\u00b3\u00f6\u017d\u00fa\u00c2\u00eb<br>
	 * Original signature : <code>int Join()</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:288</i>
	 */
	@Virtual(2) 
	native public int Join();
	/**
	 * @remark \u00d6\u00bb\u00d3\u00d0\u00b5\u00c7\u00c2\u0152\u00b3\u00c9\u00b9\u0160\u00ba\u00f3,\u00b2\u00c5\u00c4\u00dc\u00b5\u00c3\u00b5\u0153\u00d5\u00fd\u00c8\u00b7\u00b5\u00c4\u0153\u00bb\u00d2\u00d7\u00c8\u00d5<br>
	 * Original signature : <code>char* GetTradingDay()</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:293</i>
	 */
	@Virtual(3) 
	native public Pointer<Byte > GetTradingDay( ) ; // {
	//	return Pointer.pointerToAddress(GetTradingDay$2(), Byte.class);
	//}
	//@Ptr
	//@Name("GetTradingDay")
	//@Virtual(3)
	//protected native long GetTradingDay$2();
	/**
	 * @remark \u00a1\u00b0tcp\u00a1\u00b1\u017d\u00fa\u00b1\u00ed\u017d\u00ab\u00ca\u00e4\u00d0\u00ad\u00d2\u00e9\u00a3\u00ac\u00a1\u00b0127.0.0.1\u00a1\u00b1\u017d\u00fa\u00b1\u00ed\u00b7\u00fe\u00ce\u00f1\u00c6\u00f7\u00b5\u00d8\u00d6\u00b7\u00a1\u00a3\u00a1\u00b117001\u00a1\u00b1\u017d\u00fa\u00b1\u00ed\u00b7\u00fe\u00ce\u00f1\u00c6\u00f7\u00b6\u00cb\u00bf\u00da\u00ba\u00c5\u00a1\u00a3<br>
	 * Original signature : <code>void RegisterFront(char*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:299</i>
	 */
	@Virtual(4) 
	native public void RegisterFront(Pointer<Byte > pszFrontAddress) ; // {
	//	RegisterFront(Pointer.getPeer(pszFrontAddress));
	//}
	//@Virtual(4)
	//protected native void RegisterFront(@Ptr long pszFrontAddress);
	/**
	 * @remark RegisterNameServer\u00d3\u00c5\u00cf\u00c8\u00d3\u00daRegisterFront<br>
	 * Original signature : <code>void RegisterNameServer(char*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:307</i>
	 */
	@Virtual(5) 
	native public void RegisterNameServer(Pointer<Byte > pszNameServerAddress) ; // {
	//	RegisterNameServer(Pointer.getPeer(pszNameServerAddress));
	//}
	//@Virtual(5)
	//protected native void RegisterNameServer(@Ptr long pszNameServerAddress);
	/**
	 * @param pSpi \u00c5\u00c9\u00c9\u00fa\u00d7\u00d4\u00bb\u00d8\u00b5\u00f7\u0153\u00d3\u00bf\u00da\u00c0\u00e0\u00b5\u00c4\u00ca\u00b5\u00c0\u00fd<br>
	 * Original signature : <code>void RegisterSpi(CThostFtdcTraderSpi*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:311</i>
	 */
	@Virtual(6) 
	public void RegisterSpi(Pointer<CThostFtdcTraderSpi > pSpi) {
		RegisterSpi(Pointer.getPeer(pSpi));
	}
	@Virtual(6) 
	protected native void RegisterSpi(@Ptr long pSpi);
	/**
	 * @remark \u017e\u00c3\u00b7\u0153\u00b7\u0161\u00d2\u00aa\u00d4\u00daInit\u00b7\u0153\u00b7\u0161\u00c7\u00b0\u00b5\u00f7\u00d3\u00c3\u00a1\u00a3\u00c8\u00f4\u00b2\u00bb\u00b5\u00f7\u00d3\u00c3\u00d4\u00f2\u00b2\u00bb\u00bb\u00e1\u00ca\u00d5\u00b5\u0153\u00cb\u0153\u00d3\u00d0\u00c1\u00f7\u00b5\u00c4\u00ca\u00fd\u0178\u00dd\u00a1\u00a3<br>
	 * Original signature : <code>void SubscribePrivateTopic(THOST_TE_RESUME_TYPE)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:319</i>
	 */
	@Virtual(7) 
	public void SubscribePrivateTopic(IntValuedEnum<THOST_TE_RESUME_TYPE > nResumeType) {
		SubscribePrivateTopic((int)nResumeType.value());
	}
	@Virtual(7) 
	protected native void SubscribePrivateTopic(int nResumeType);
	/**
	 * @remark \u017e\u00c3\u00b7\u0153\u00b7\u0161\u00d2\u00aa\u00d4\u00daInit\u00b7\u0153\u00b7\u0161\u00c7\u00b0\u00b5\u00f7\u00d3\u00c3\u00a1\u00a3\u00c8\u00f4\u00b2\u00bb\u00b5\u00f7\u00d3\u00c3\u00d4\u00f2\u00b2\u00bb\u00bb\u00e1\u00ca\u00d5\u00b5\u0153\u00b9\u00ab\u00b9\u00b2\u00c1\u00f7\u00b5\u00c4\u00ca\u00fd\u0178\u00dd\u00a1\u00a3<br>
	 * Original signature : <code>void SubscribePublicTopic(THOST_TE_RESUME_TYPE)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:327</i>
	 */
	@Virtual(8) 
	public void SubscribePublicTopic(IntValuedEnum<THOST_TE_RESUME_TYPE > nResumeType) {
		SubscribePublicTopic((int)nResumeType.value());
	}
	@Virtual(8) 
	protected native void SubscribePublicTopic(int nResumeType);
	/**
	 * \u00bf\u00cd\u00bb\u00a7\u00b6\u00cb\u00c8\u00cf\u00d6\u20ac\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqAuthenticate(CThostFtdcReqAuthenticateField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:330</i>
	 */
	@Virtual(9) 
	public int ReqAuthenticate(Pointer<CThostFtdcReqAuthenticateField > pReqAuthenticateField, int nRequestID) {
		return ReqAuthenticate(Pointer.getPeer(pReqAuthenticateField), nRequestID);
	}
	@Virtual(9) 
	protected native int ReqAuthenticate(@Ptr long pReqAuthenticateField, int nRequestID);
	/**
	 * \u00d3\u00c3\u00bb\u00a7\u00b5\u00c7\u00c2\u0152\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqUserLogin(CThostFtdcReqUserLoginField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:333</i>
	 */
	@Virtual(10) 
	public int ReqUserLogin(Pointer<CThostFtdcReqUserLoginField > pReqUserLoginField, int nRequestID) {
		return ReqUserLogin(Pointer.getPeer(pReqUserLoginField), nRequestID);
	}
	@Virtual(10) 
	protected native int ReqUserLogin(@Ptr long pReqUserLoginField, int nRequestID);
	/**
	 * \u00b5\u00c7\u00b3\u00f6\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqUserLogout(CThostFtdcUserLogoutField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:336</i>
	 */
	@Virtual(11) 
	public int ReqUserLogout(Pointer<CThostFtdcUserLogoutField > pUserLogout, int nRequestID) {
		return ReqUserLogout(Pointer.getPeer(pUserLogout), nRequestID);
	}
	@Virtual(11) 
	protected native int ReqUserLogout(@Ptr long pUserLogout, int nRequestID);
	/**
	 * \u00d3\u00c3\u00bb\u00a7\u00bf\u00da\u00c1\u00ee\u017e\u00fc\u00d0\u00c2\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqUserPasswordUpdate(CThostFtdcUserPasswordUpdateField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:339</i>
	 */
	@Virtual(12) 
	public int ReqUserPasswordUpdate(Pointer<CThostFtdcUserPasswordUpdateField > pUserPasswordUpdate, int nRequestID) {
		return ReqUserPasswordUpdate(Pointer.getPeer(pUserPasswordUpdate), nRequestID);
	}
	@Virtual(12) 
	protected native int ReqUserPasswordUpdate(@Ptr long pUserPasswordUpdate, int nRequestID);
	/**
	 * \u00d7\u00ca\u0153\u00f0\u00d5\u00cb\u00bb\u00a7\u00bf\u00da\u00c1\u00ee\u017e\u00fc\u00d0\u00c2\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqTradingAccountPasswordUpdate(CThostFtdcTradingAccountPasswordUpdateField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:342</i>
	 */
	@Virtual(13) 
	public int ReqTradingAccountPasswordUpdate(Pointer<CThostFtdcTradingAccountPasswordUpdateField > pTradingAccountPasswordUpdate, int nRequestID) {
		return ReqTradingAccountPasswordUpdate(Pointer.getPeer(pTradingAccountPasswordUpdate), nRequestID);
	}
	@Virtual(13) 
	protected native int ReqTradingAccountPasswordUpdate(@Ptr long pTradingAccountPasswordUpdate, int nRequestID);
	/**
	 * \u00b1\u0161\u00b5\u00a5\u00c2\u0152\u00c8\u00eb\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqOrderInsert(CThostFtdcInputOrderField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:345</i>
	 */
	@Virtual(14) 
	public int ReqOrderInsert(Pointer<CThostFtdcInputOrderField > pInputOrder, int nRequestID) {
		return ReqOrderInsert(Pointer.getPeer(pInputOrder), nRequestID);
	}
	@Virtual(14) 
	protected native int ReqOrderInsert(@Ptr long pInputOrder, int nRequestID);
	/**
	 * \u00d4\u20ac\u00c2\u00f1\u00b5\u00a5\u00c2\u0152\u00c8\u00eb\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqParkedOrderInsert(CThostFtdcParkedOrderField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:348</i>
	 */
	@Virtual(15) 
	public int ReqParkedOrderInsert(Pointer<CThostFtdcParkedOrderField > pParkedOrder, int nRequestID) {
		return ReqParkedOrderInsert(Pointer.getPeer(pParkedOrder), nRequestID);
	}
	@Virtual(15) 
	protected native int ReqParkedOrderInsert(@Ptr long pParkedOrder, int nRequestID);
	/**
	 * \u00d4\u20ac\u00c2\u00f1\u00b3\u00b7\u00b5\u00a5\u00c2\u0152\u00c8\u00eb\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqParkedOrderAction(CThostFtdcParkedOrderActionField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:351</i>
	 */
	@Virtual(16) 
	public int ReqParkedOrderAction(Pointer<CThostFtdcParkedOrderActionField > pParkedOrderAction, int nRequestID) {
		return ReqParkedOrderAction(Pointer.getPeer(pParkedOrderAction), nRequestID);
	}
	@Virtual(16) 
	protected native int ReqParkedOrderAction(@Ptr long pParkedOrderAction, int nRequestID);
	/**
	 * \u00b1\u0161\u00b5\u00a5\u00b2\u00d9\u00d7\u00f7\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqOrderAction(CThostFtdcInputOrderActionField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:354</i>
	 */
	@Virtual(17) 
	public int ReqOrderAction(Pointer<CThostFtdcInputOrderActionField > pInputOrderAction, int nRequestID) {
		return ReqOrderAction(Pointer.getPeer(pInputOrderAction), nRequestID);
	}
	@Virtual(17) 
	protected native int ReqOrderAction(@Ptr long pInputOrderAction, int nRequestID);
	/**
	 * \u00b2\u00e9\u00d1\u00af\u00d7\u00ee\u017d\u00f3\u00b1\u0161\u00b5\u00a5\u00ca\u00fd\u00c1\u00bf\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqQueryMaxOrderVolume(CThostFtdcQueryMaxOrderVolumeField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:357</i>
	 */
	@Virtual(18) 
	public int ReqQueryMaxOrderVolume(Pointer<CThostFtdcQueryMaxOrderVolumeField > pQueryMaxOrderVolume, int nRequestID) {
		return ReqQueryMaxOrderVolume(Pointer.getPeer(pQueryMaxOrderVolume), nRequestID);
	}
	@Virtual(18) 
	protected native int ReqQueryMaxOrderVolume(@Ptr long pQueryMaxOrderVolume, int nRequestID);
	/**
	 * \u00cd\u00b6\u00d7\u00ca\u00d5\u00df\u0153\u00e1\u00cb\u00e3\u0153\u00e1\u00b9\u00fb\u00c8\u00b7\u00c8\u00cf<br>
	 * Original signature : <code>int ReqSettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:360</i>
	 */
	@Virtual(19) 
	native public int ReqSettlementInfoConfirm(Pointer<CThostFtdcSettlementInfoConfirmField > pSettlementInfoConfirm, int nRequestID) ; // {
	//	return ReqSettlementInfoConfirm(Pointer.getPeer(pSettlementInfoConfirm), nRequestID);
	//}
	//@Virtual(19)
	//protected native int ReqSettlementInfoConfirm(@Ptr long pSettlementInfoConfirm, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00c9\u0178\u00b3\u00fd\u00d4\u20ac\u00c2\u00f1\u00b5\u00a5<br>
	 * Original signature : <code>int ReqRemoveParkedOrder(CThostFtdcRemoveParkedOrderField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:363</i>
	 */
	@Virtual(20) 
	public int ReqRemoveParkedOrder(Pointer<CThostFtdcRemoveParkedOrderField > pRemoveParkedOrder, int nRequestID) {
		return ReqRemoveParkedOrder(Pointer.getPeer(pRemoveParkedOrder), nRequestID);
	}
	@Virtual(20) 
	protected native int ReqRemoveParkedOrder(@Ptr long pRemoveParkedOrder, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00c9\u0178\u00b3\u00fd\u00d4\u20ac\u00c2\u00f1\u00b3\u00b7\u00b5\u00a5<br>
	 * Original signature : <code>int ReqRemoveParkedOrderAction(CThostFtdcRemoveParkedOrderActionField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:366</i>
	 */
	@Virtual(21) 
	public int ReqRemoveParkedOrderAction(Pointer<CThostFtdcRemoveParkedOrderActionField > pRemoveParkedOrderAction, int nRequestID) {
		return ReqRemoveParkedOrderAction(Pointer.getPeer(pRemoveParkedOrderAction), nRequestID);
	}
	@Virtual(21) 
	protected native int ReqRemoveParkedOrderAction(@Ptr long pRemoveParkedOrderAction, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00b1\u0161\u00b5\u00a5<br>
	 * Original signature : <code>int ReqQryOrder(CThostFtdcQryOrderField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:369</i>
	 */
	@Virtual(22) 
	public int ReqQryOrder(Pointer<CThostFtdcQryOrderField > pQryOrder, int nRequestID) {
		return ReqQryOrder(Pointer.getPeer(pQryOrder), nRequestID);
	}
	@Virtual(22) 
	protected native int ReqQryOrder(@Ptr long pQryOrder, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00b3\u00c9\u0153\u00bb<br>
	 * Original signature : <code>int ReqQryTrade(CThostFtdcQryTradeField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:372</i>
	 */
	@Virtual(23) 
	public int ReqQryTrade(Pointer<CThostFtdcQryTradeField > pQryTrade, int nRequestID) {
		return ReqQryTrade(Pointer.getPeer(pQryTrade), nRequestID);
	}
	@Virtual(23) 
	protected native int ReqQryTrade(@Ptr long pQryTrade, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00cd\u00b6\u00d7\u00ca\u00d5\u00df\u00b3\u00d6\u00b2\u00d6<br>
	 * Original signature : <code>int ReqQryInvestorPosition(CThostFtdcQryInvestorPositionField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:375</i>
	 */
	@Virtual(24) 
	public int ReqQryInvestorPosition(Pointer<CThostFtdcQryInvestorPositionField > pQryInvestorPosition, int nRequestID) {
		return ReqQryInvestorPosition(Pointer.getPeer(pQryInvestorPosition), nRequestID);
	}
	@Virtual(24) 
	protected native int ReqQryInvestorPosition(@Ptr long pQryInvestorPosition, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d7\u00ca\u0153\u00f0\u00d5\u00cb\u00bb\u00a7<br>
	 * Original signature : <code>int ReqQryTradingAccount(CThostFtdcQryTradingAccountField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:378</i>
	 */
	@Virtual(25) 
	public int ReqQryTradingAccount(Pointer<CThostFtdcQryTradingAccountField > pQryTradingAccount, int nRequestID) {
		return ReqQryTradingAccount(Pointer.getPeer(pQryTradingAccount), nRequestID);
	}
	@Virtual(25) 
	protected native int ReqQryTradingAccount(@Ptr long pQryTradingAccount, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00cd\u00b6\u00d7\u00ca\u00d5\u00df<br>
	 * Original signature : <code>int ReqQryInvestor(CThostFtdcQryInvestorField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:381</i>
	 */
	@Virtual(26) 
	public int ReqQryInvestor(Pointer<CThostFtdcQryInvestorField > pQryInvestor, int nRequestID) {
		return ReqQryInvestor(Pointer.getPeer(pQryInvestor), nRequestID);
	}
	@Virtual(26) 
	protected native int ReqQryInvestor(@Ptr long pQryInvestor, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0153\u00bb\u00d2\u00d7\u00b1\u00e0\u00c2\u00eb<br>
	 * Original signature : <code>int ReqQryTradingCode(CThostFtdcQryTradingCodeField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:384</i>
	 */
	@Virtual(27) 
	public int ReqQryTradingCode(Pointer<CThostFtdcQryTradingCodeField > pQryTradingCode, int nRequestID) {
		return ReqQryTradingCode(Pointer.getPeer(pQryTradingCode), nRequestID);
	}
	@Virtual(27) 
	protected native int ReqQryTradingCode(@Ptr long pQryTradingCode, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00ba\u00cf\u00d4\u0152\u00b1\u00a3\u00d6\u20ac\u0153\u00f0\u00c2\u00ca<br>
	 * Original signature : <code>int ReqQryInstrumentMarginRate(CThostFtdcQryInstrumentMarginRateField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:387</i>
	 */
	@Virtual(28) 
	public int ReqQryInstrumentMarginRate(Pointer<CThostFtdcQryInstrumentMarginRateField > pQryInstrumentMarginRate, int nRequestID) {
		return ReqQryInstrumentMarginRate(Pointer.getPeer(pQryInstrumentMarginRate), nRequestID);
	}
	@Virtual(28) 
	protected native int ReqQryInstrumentMarginRate(@Ptr long pQryInstrumentMarginRate, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00ba\u00cf\u00d4\u0152\u00ca\u00d6\u00d0\u00f8\u00b7\u00d1\u00c2\u00ca<br>
	 * Original signature : <code>int ReqQryInstrumentCommissionRate(CThostFtdcQryInstrumentCommissionRateField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:390</i>
	 */
	@Virtual(29) 
	public int ReqQryInstrumentCommissionRate(Pointer<CThostFtdcQryInstrumentCommissionRateField > pQryInstrumentCommissionRate, int nRequestID) {
		return ReqQryInstrumentCommissionRate(Pointer.getPeer(pQryInstrumentCommissionRate), nRequestID);
	}
	@Virtual(29) 
	protected native int ReqQryInstrumentCommissionRate(@Ptr long pQryInstrumentCommissionRate, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0153\u00bb\u00d2\u00d7\u00cb\u00f9<br>
	 * Original signature : <code>int ReqQryExchange(CThostFtdcQryExchangeField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:393</i>
	 */
	@Virtual(30) 
	public int ReqQryExchange(Pointer<CThostFtdcQryExchangeField > pQryExchange, int nRequestID) {
		return ReqQryExchange(Pointer.getPeer(pQryExchange), nRequestID);
	}
	@Virtual(30) 
	protected native int ReqQryExchange(@Ptr long pQryExchange, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00ba\u00cf\u00d4\u0152<br>
	 * Original signature : <code>int ReqQryInstrument(CThostFtdcQryInstrumentField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:396</i>
	 */
	@Virtual(31) 
	public int ReqQryInstrument(Pointer<CThostFtdcQryInstrumentField > pQryInstrument, int nRequestID) {
		return ReqQryInstrument(Pointer.getPeer(pQryInstrument), nRequestID);
	}
	@Virtual(31) 
	protected native int ReqQryInstrument(@Ptr long pQryInstrument, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d0\u00d0\u00c7\u00e9<br>
	 * Original signature : <code>int ReqQryDepthMarketData(CThostFtdcQryDepthMarketDataField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:399</i>
	 */
	@Virtual(32) 
	public int ReqQryDepthMarketData(Pointer<CThostFtdcQryDepthMarketDataField > pQryDepthMarketData, int nRequestID) {
		return ReqQryDepthMarketData(Pointer.getPeer(pQryDepthMarketData), nRequestID);
	}
	@Virtual(32) 
	protected native int ReqQryDepthMarketData(@Ptr long pQryDepthMarketData, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00cd\u00b6\u00d7\u00ca\u00d5\u00df\u0153\u00e1\u00cb\u00e3\u0153\u00e1\u00b9\u00fb<br>
	 * Original signature : <code>int ReqQrySettlementInfo(CThostFtdcQrySettlementInfoField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:402</i>
	 */
	@Virtual(33) 
	public int ReqQrySettlementInfo(Pointer<CThostFtdcQrySettlementInfoField > pQrySettlementInfo, int nRequestID) {
		return ReqQrySettlementInfo(Pointer.getPeer(pQrySettlementInfo), nRequestID);
	}
	@Virtual(33) 
	protected native int ReqQrySettlementInfo(@Ptr long pQrySettlementInfo, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d7\u00aa\u00d5\u00ca\u00d2\u00f8\u00d0\u00d0<br>
	 * Original signature : <code>int ReqQryTransferBank(CThostFtdcQryTransferBankField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:405</i>
	 */
	@Virtual(34) 
	public int ReqQryTransferBank(Pointer<CThostFtdcQryTransferBankField > pQryTransferBank, int nRequestID) {
		return ReqQryTransferBank(Pointer.getPeer(pQryTransferBank), nRequestID);
	}
	@Virtual(34) 
	protected native int ReqQryTransferBank(@Ptr long pQryTransferBank, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00cd\u00b6\u00d7\u00ca\u00d5\u00df\u00b3\u00d6\u00b2\u00d6\u00c3\u00f7\u00cf\u017e<br>
	 * Original signature : <code>int ReqQryInvestorPositionDetail(CThostFtdcQryInvestorPositionDetailField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:408</i>
	 */
	@Virtual(35) 
	public int ReqQryInvestorPositionDetail(Pointer<CThostFtdcQryInvestorPositionDetailField > pQryInvestorPositionDetail, int nRequestID) {
		return ReqQryInvestorPositionDetail(Pointer.getPeer(pQryInvestorPositionDetail), nRequestID);
	}
	@Virtual(35) 
	protected native int ReqQryInvestorPositionDetail(@Ptr long pQryInvestorPositionDetail, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00bf\u00cd\u00bb\u00a7\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>int ReqQryNotice(CThostFtdcQryNoticeField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:411</i>
	 */
	@Virtual(36) 
	public int ReqQryNotice(Pointer<CThostFtdcQryNoticeField > pQryNotice, int nRequestID) {
		return ReqQryNotice(Pointer.getPeer(pQryNotice), nRequestID);
	}
	@Virtual(36) 
	protected native int ReqQryNotice(@Ptr long pQryNotice, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0153\u00e1\u00cb\u00e3\u00d0\u00c5\u00cf\u00a2\u00c8\u00b7\u00c8\u00cf<br>
	 * Original signature : <code>int ReqQrySettlementInfoConfirm(CThostFtdcQrySettlementInfoConfirmField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:414</i>
	 */
	@Virtual(37) 
	public int ReqQrySettlementInfoConfirm(Pointer<CThostFtdcQrySettlementInfoConfirmField > pQrySettlementInfoConfirm, int nRequestID) {
		return ReqQrySettlementInfoConfirm(Pointer.getPeer(pQrySettlementInfoConfirm), nRequestID);
	}
	@Virtual(37) 
	protected native int ReqQrySettlementInfoConfirm(@Ptr long pQrySettlementInfoConfirm, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00cd\u00b6\u00d7\u00ca\u00d5\u00df\u00b3\u00d6\u00b2\u00d6\u00c3\u00f7\u00cf\u017e<br>
	 * Original signature : <code>int ReqQryInvestorPositionCombineDetail(CThostFtdcQryInvestorPositionCombineDetailField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:417</i>
	 */
	@Virtual(38) 
	public int ReqQryInvestorPositionCombineDetail(Pointer<CThostFtdcQryInvestorPositionCombineDetailField > pQryInvestorPositionCombineDetail, int nRequestID) {
		return ReqQryInvestorPositionCombineDetail(Pointer.getPeer(pQryInvestorPositionCombineDetail), nRequestID);
	}
	@Virtual(38) 
	protected native int ReqQryInvestorPositionCombineDetail(@Ptr long pQryInvestorPositionCombineDetail, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00b1\u00a3\u00d6\u20ac\u0153\u00f0\u0152\u00e0\u00b9\u00dc\u00cf\u00b5\u00cd\u00b3\u0178\u00ad\u0152\u00cd\u00b9\u00ab\u00cb\u0178\u00d7\u00ca\u0153\u00f0\u00d5\u00cb\u00bb\u00a7\u00c3\u00dc\u00d4\u00bf<br>
	 * Original signature : <code>int ReqQryCFMMCTradingAccountKey(CThostFtdcQryCFMMCTradingAccountKeyField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:420</i>
	 */
	@Virtual(39) 
	public int ReqQryCFMMCTradingAccountKey(Pointer<CThostFtdcQryCFMMCTradingAccountKeyField > pQryCFMMCTradingAccountKey, int nRequestID) {
		return ReqQryCFMMCTradingAccountKey(Pointer.getPeer(pQryCFMMCTradingAccountKey), nRequestID);
	}
	@Virtual(39) 
	protected native int ReqQryCFMMCTradingAccountKey(@Ptr long pQryCFMMCTradingAccountKey, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00b2\u00d6\u00b5\u00a5\u00d5\u00db\u00b5\u00d6\u00d0\u00c5\u00cf\u00a2<br>
	 * Original signature : <code>int ReqQryEWarrantOffset(CThostFtdcQryEWarrantOffsetField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:423</i>
	 */
	@Virtual(40) 
	public int ReqQryEWarrantOffset(Pointer<CThostFtdcQryEWarrantOffsetField > pQryEWarrantOffset, int nRequestID) {
		return ReqQryEWarrantOffset(Pointer.getPeer(pQryEWarrantOffset), nRequestID);
	}
	@Virtual(40) 
	protected native int ReqQryEWarrantOffset(@Ptr long pQryEWarrantOffset, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d7\u00aa\u00d5\u00ca\u00c1\u00f7\u00cb\u00ae<br>
	 * Original signature : <code>int ReqQryTransferSerial(CThostFtdcQryTransferSerialField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:426</i>
	 */
	@Virtual(41) 
	public int ReqQryTransferSerial(Pointer<CThostFtdcQryTransferSerialField > pQryTransferSerial, int nRequestID) {
		return ReqQryTransferSerial(Pointer.getPeer(pQryTransferSerial), nRequestID);
	}
	@Virtual(41) 
	protected native int ReqQryTransferSerial(@Ptr long pQryTransferSerial, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d2\u00f8\u00c6\u00da\u00c7\u00a9\u00d4\u0152\u00b9\u00d8\u00cf\u00b5<br>
	 * Original signature : <code>int ReqQryAccountregister(CThostFtdcQryAccountregisterField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:429</i>
	 */
	@Virtual(42) 
	public int ReqQryAccountregister(Pointer<CThostFtdcQryAccountregisterField > pQryAccountregister, int nRequestID) {
		return ReqQryAccountregister(Pointer.getPeer(pQryAccountregister), nRequestID);
	}
	@Virtual(42) 
	protected native int ReqQryAccountregister(@Ptr long pQryAccountregister, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00c7\u00a9\u00d4\u0152\u00d2\u00f8\u00d0\u00d0<br>
	 * Original signature : <code>int ReqQryContractBank(CThostFtdcQryContractBankField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:432</i>
	 */
	@Virtual(43) 
	public int ReqQryContractBank(Pointer<CThostFtdcQryContractBankField > pQryContractBank, int nRequestID) {
		return ReqQryContractBank(Pointer.getPeer(pQryContractBank), nRequestID);
	}
	@Virtual(43) 
	protected native int ReqQryContractBank(@Ptr long pQryContractBank, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d4\u20ac\u00c2\u00f1\u00b5\u00a5<br>
	 * Original signature : <code>int ReqQryParkedOrder(CThostFtdcQryParkedOrderField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:435</i>
	 */
	@Virtual(44) 
	public int ReqQryParkedOrder(Pointer<CThostFtdcQryParkedOrderField > pQryParkedOrder, int nRequestID) {
		return ReqQryParkedOrder(Pointer.getPeer(pQryParkedOrder), nRequestID);
	}
	@Virtual(44) 
	protected native int ReqQryParkedOrder(@Ptr long pQryParkedOrder, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u00d4\u20ac\u00c2\u00f1\u00b3\u00b7\u00b5\u00a5<br>
	 * Original signature : <code>int ReqQryParkedOrderAction(CThostFtdcQryParkedOrderActionField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:438</i>
	 */
	@Virtual(45) 
	public int ReqQryParkedOrderAction(Pointer<CThostFtdcQryParkedOrderActionField > pQryParkedOrderAction, int nRequestID) {
		return ReqQryParkedOrderAction(Pointer.getPeer(pQryParkedOrderAction), nRequestID);
	}
	@Virtual(45) 
	protected native int ReqQryParkedOrderAction(@Ptr long pQryParkedOrderAction, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0153\u00bb\u00d2\u00d7\u00cd\u0161\u00d6\u00aa<br>
	 * Original signature : <code>int ReqQryTradingNotice(CThostFtdcQryTradingNoticeField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:441</i>
	 */
	@Virtual(46) 
	public int ReqQryTradingNotice(Pointer<CThostFtdcQryTradingNoticeField > pQryTradingNotice, int nRequestID) {
		return ReqQryTradingNotice(Pointer.getPeer(pQryTradingNotice), nRequestID);
	}
	@Virtual(46) 
	protected native int ReqQryTradingNotice(@Ptr long pQryTradingNotice, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0178\u00ad\u0152\u00cd\u00b9\u00ab\u00cb\u0178\u0153\u00bb\u00d2\u00d7\u00b2\u00ce\u00ca\u00fd<br>
	 * Original signature : <code>int ReqQryBrokerTradingParams(CThostFtdcQryBrokerTradingParamsField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:444</i>
	 */
	@Virtual(47) 
	public int ReqQryBrokerTradingParams(Pointer<CThostFtdcQryBrokerTradingParamsField > pQryBrokerTradingParams, int nRequestID) {
		return ReqQryBrokerTradingParams(Pointer.getPeer(pQryBrokerTradingParams), nRequestID);
	}
	@Virtual(47) 
	protected native int ReqQryBrokerTradingParams(@Ptr long pQryBrokerTradingParams, int nRequestID);
	/**
	 * \u00c7\u00eb\u00c7\u00f3\u00b2\u00e9\u00d1\u00af\u0178\u00ad\u0152\u00cd\u00b9\u00ab\u00cb\u0178\u0153\u00bb\u00d2\u00d7\u00cb\u00e3\u00b7\u0161<br>
	 * Original signature : <code>int ReqQryBrokerTradingAlgos(CThostFtdcQryBrokerTradingAlgosField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:447</i>
	 */
	@Virtual(48) 
	public int ReqQryBrokerTradingAlgos(Pointer<CThostFtdcQryBrokerTradingAlgosField > pQryBrokerTradingAlgos, int nRequestID) {
		return ReqQryBrokerTradingAlgos(Pointer.getPeer(pQryBrokerTradingAlgos), nRequestID);
	}
	@Virtual(48) 
	protected native int ReqQryBrokerTradingAlgos(@Ptr long pQryBrokerTradingAlgos, int nRequestID);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00d2\u00f8\u00d0\u00d0\u00d7\u00ca\u0153\u00f0\u00d7\u00aa\u00c6\u00da\u00bb\u00f5\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqFromBankToFutureByFuture(CThostFtdcReqTransferField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:450</i>
	 */
	@Virtual(49) 
	public int ReqFromBankToFutureByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, int nRequestID) {
		return ReqFromBankToFutureByFuture(Pointer.getPeer(pReqTransfer), nRequestID);
	}
	@Virtual(49) 
	protected native int ReqFromBankToFutureByFuture(@Ptr long pReqTransfer, int nRequestID);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00c6\u00da\u00bb\u00f5\u00d7\u00ca\u0153\u00f0\u00d7\u00aa\u00d2\u00f8\u00d0\u00d0\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqFromFutureToBankByFuture(CThostFtdcReqTransferField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:453</i>
	 */
	@Virtual(50) 
	public int ReqFromFutureToBankByFuture(Pointer<CThostFtdcReqTransferField > pReqTransfer, int nRequestID) {
		return ReqFromFutureToBankByFuture(Pointer.getPeer(pReqTransfer), nRequestID);
	}
	@Virtual(50) 
	protected native int ReqFromFutureToBankByFuture(@Ptr long pReqTransfer, int nRequestID);
	/**
	 * \u00c6\u00da\u00bb\u00f5\u00b7\u00a2\u00c6\u00f0\u00b2\u00e9\u00d1\u00af\u00d2\u00f8\u00d0\u00d0\u00d3\u00e0\u00b6\u00ee\u00c7\u00eb\u00c7\u00f3<br>
	 * Original signature : <code>int ReqQueryBankAccountMoneyByFuture(CThostFtdcReqQueryAccountField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:456</i>
	 */
	@Virtual(51) 
	public int ReqQueryBankAccountMoneyByFuture(Pointer<CThostFtdcReqQueryAccountField > pReqQueryAccount, int nRequestID) {
		return ReqQueryBankAccountMoneyByFuture(Pointer.getPeer(pReqQueryAccount), nRequestID);
	}
	@Virtual(51) 
	protected native int ReqQueryBankAccountMoneyByFuture(@Ptr long pReqQueryAccount, int nRequestID);
	/**
	 * \u00b2\u00e9\u00d1\u00af\u00bf\u00aa\u00c5\u00cc\u00c7\u00b0\u00b5\u00c4\u00b3\u00d6\u00b2\u00d6\u00c3\u00f7\u00cf\u017e(20110808)<br>
	 * Original signature : <code>int ReqQueryInvestorOpenPosition(CThostFtdcQryInvestorPositionDetailField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:459</i>
	 */
	@Virtual(52) 
	public int ReqQueryInvestorOpenPosition(Pointer<CThostFtdcQryInvestorPositionDetailField > pQryInvestorOpenPosition, int nRequestID) {
		return ReqQueryInvestorOpenPosition(Pointer.getPeer(pQryInvestorOpenPosition), nRequestID);
	}
	@Virtual(52) 
	protected native int ReqQueryInvestorOpenPosition(@Ptr long pQryInvestorOpenPosition, int nRequestID);
	/**
	 * \u00b2\u00e9\u00d1\u00af\u00bf\u00aa\u00c5\u00cc\u00c7\u00b0\u00b5\u00c4\u00d7\u00e9\u00ba\u00cf\u00b3\u00d6\u00b2\u00d6\u00c3\u00f7\u00cf\u017e(20110808)<br>
	 * Original signature : <code>int ReqQueryInvestorOpenCombinePosition(CThostFtdcQryInvestorPositionCombineDetailField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:462</i>
	 */
	@Virtual(53) 
	public int ReqQueryInvestorOpenCombinePosition(Pointer<CThostFtdcQryInvestorPositionCombineDetailField > pQryInvestorOpenCombinePosition, int nRequestID) {
		return ReqQueryInvestorOpenCombinePosition(Pointer.getPeer(pQryInvestorOpenCombinePosition), nRequestID);
	}
	@Virtual(53) 
	protected native int ReqQueryInvestorOpenCombinePosition(@Ptr long pQryInvestorOpenCombinePosition, int nRequestID);
	/**
	 * \u00c9\u00e8\u00d6\u00c3\u00b5\u00b1\u00c7\u00b0\u00bf\u00c9\u00b6\u00c1\u00d0\u017d\u00c2\u00b7\u0178\u00b6<br>
	 * Original signature : <code>int SetWritablePath(const char*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:465</i>
	 */
	@Virtual(54) 
	public int SetWritablePath(Pointer<Byte > szpath) {
		return SetWritablePath(Pointer.getPeer(szpath));
	}
	@Virtual(54) 
	protected native int SetWritablePath(@Ptr long szpath);
	/**
	 * \u00d7\u00a2\u00b2\u00e1\u00cc\u00f5\u0152\u00fe\u00b5\u00a5\u00ca\u00b5\u00c0\u00fd<br>
	 * Original signature : <code>void* LoadExtApi(void*, const char*)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:468</i>
	 */
	@Virtual(55) 
	public Pointer<? > LoadExtApi(Pointer<? > spi, Pointer<Byte > ExtApiName) {
		return Pointer.pointerToAddress(LoadExtApi(Pointer.getPeer(spi), Pointer.getPeer(ExtApiName)));
	}
	@Ptr 
	@Virtual(55) 
	protected native long LoadExtApi(@Ptr long spi, @Ptr long ExtApiName);
	/**
	 * \u00c5\u00fa\u00c1\u00bf\u00b3\u00b7\u00b5\u00a5<br>
	 * Original signature : <code>int ReqBulkCancelOrder(CThostFtdcBulkCancelOrderField*, int)</code><br>
	 * <i>native declaration : linuxapi/CTP/kstradeapija.h:471</i>
	 */
	@Virtual(56) 
	public int ReqBulkCancelOrder(Pointer<CThostFtdcBulkCancelOrderField > pBulkCancelOrder, int nRequestID) {
		return ReqBulkCancelOrder(Pointer.getPeer(pBulkCancelOrder), nRequestID);
	}
	@Virtual(56) 
	protected native int ReqBulkCancelOrder(@Ptr long pBulkCancelOrder, int nRequestID);
	public CThostFtdcTraderApi() {
		super();
	}
	public CThostFtdcTraderApi(Pointer pointer) {
		super(pointer);
	}
}
